---
output:
  pdf_document: default
  html_document: default
---

## 1. Breath alcohol tests in Ames, Iowa, USA
Ames, Iowa, USA is the home of Iowa State University, a land grant university with over 36,000 students. By comparison, the city of Ames, Iowa, itself only has about 65,000 residents. As with any other college town, Ames has had its fair share of alcohol-related incidents. (For example, Google 'VEISHEA riots 2014'.) We will take a look at some breath alcohol test data from Ames that is published by the State of Iowa.

The data file 'breath_alcohol_ames.csv' contains 1,556 readings from breath alcohol tests administered by the Ames and Iowa State University Police Departments from January 2013 to December 2017. The columns in this data set are year, month, day, hour, location, gender, Res1, Res2.


```R
# load the tidyverse suite of packages 
library(tidyverse)

# read the data into your workspace
ba_data <- read_csv("datasets/breath_alcohol_ames.csv")

# quickly inspect the data
head(ba_data)

# obtain counts for each year 
ba_year<- ba_data %>% group_by(year) %>%
summarise( n =n())
```

    -- Attaching packages --------------------------------------- tidyverse 1.2.1 --
    <U+221A> ggplot2 3.0.0     <U+221A> purrr   0.2.5
    <U+221A> tibble  1.4.2     <U+221A> dplyr   0.7.6
    <U+221A> tidyr   0.8.1     <U+221A> stringr 1.3.1
    <U+221A> readr   1.1.1     <U+221A> forcats 0.3.0
    -- Conflicts ------------------------------------------ tidyverse_conflicts() --
    x dplyr::filter() masks stats::filter()
    x dplyr::lag()    masks stats::lag()
    Parsed with column specification:
    cols(
      year = col_integer(),
      month = col_integer(),
      day = col_integer(),
      hour = col_integer(),
      location = col_character(),
      gender = col_character(),
      Res1 = col_double(),
      Res2 = col_double()
    )



## 2. What is the busiest police department in Ames?
There are two police departments in the data set: the Iowa State University Police Department and the Ames Police Department. Which one administers more breathalyzer tests? 


```R
# use count to tally up the totals for each department
pds <- ba_data %>% group_by(location) %>%
summarise( n =n())

pds
```

## 3. Nothing Good Happens after 2am
We all know that "nothing good happens after 2am." Thus, there are inevitably some times of the day when breath alcohol tests, especially in a college town like Ames, are most and least common. Which hours of the day have the most and least breathalyzer tests? 

```R
# count by hour and arrange by descending frequency
hourly <- ba_data %>% group_by(hour) %>%
summarise(n= n())%>%
arrange(desc(n))
hourly

# use a geom_ to create the appropriate bar chart
ggplot(hourly, aes(x= hour, weight =n)) + geom_bar()
```

## 4. Breathalyzer tests by month
Now that we have discovered which time of day is most common for breath alcohol tests, we will determine which time of the year has the most breathalyzer tests. Which month will have the most recorded tests?


```R
# count by month and arrange by descending frequency
monthly <- ba_data %>% group_by(month) %>%
summarise(n= n())%>%
arrange(desc(n))

# make month a factor
monthly$month <- as.factor(monthly$month)

# use a geom_ to create the appropriate bar chart
ggplot(monthly, aes(month, weight=n)) + geom_bar()
```



## 5. COLLEGE
When we think of (binge) drinking in college towns in America, we usually think of something like this image at the left. And so, one might suspect that breath alcohol tests are given to men more often than women and that men drink more than women.


```R
# count by gender 
ba_data %>% group_by(gender) %>%
summarise(n= n())%>%
arrange(desc(n))

# create a dataset with no NAs in gender 
clean_gender <- ba_data %>% 
filter(!is.na(gender))

head(clean_gender,2)


# create a mean test result variable and save as mean_bas
mean_bas <- clean_gender %>% mutate(meanRes = (Res1+Res2)/2)

head(mean_bas,4)

# create side-by-side boxplots to compare the mean blood alcohol levels of men and women
ggplot(mean_bas, aes(gender,meanRes)) + geom_boxplot()
```

## 6. Above the legal limit
In the USA, it is illegal to drive with a blood alcohol concentration (BAC) above 0.08%. This is the case for all 50 states. Assuming everyone tested in our data was driving (though we have no way of knowing this from the data), if either of the results (Res1,Res2) are above 0.08, the person would be charged with DUI (driving under the influence).


```R
# Filter the data
duis <- ba_data %>% filter (Res1 >0.08 | Res2 >0.08)

# proportion of tests that would have resulted in a DUI
p_dui <- nrow(duis)/nrow(ba_data)

round(p_dui,3)
```


0.745


## 7. Breathalyzer tests: is there a pattern over time?
We previously saw that 2am is the most common time of day for breathalyzer tests to be administered, and August is the most common month of the year for breathalyzer tests. Now, we look at the weeks in the year over time. We briefly use the lubridate package for a bit of date-time manipulation.


```R
library(lubridate) 

# Create date variable using paste() and ymd()
ba_data <- ba_data %>% mutate(date = ymd(paste(year,month,day)))
ba_data%>% head(2)

# Create a week variable using week()
ba_data <- ba_data %>% mutate(week = week(date))
ba_data%>% head(2)
```
## 8. Looking at timelines
How do the weeks differ over time? One of the most common data visualizations is the time series, a line tracking the changes in a variable over time. We will use the new "week" variable to look at test frequency over time. We end with a time series plot showing frequency of breathalyzer tests by week in year, with one line for each year. 


```R
# create the weekly data set 
weekly <- ba_data %>% group_by(year,week)%>%
summarise(n =n())

head(weekly,2)

weekly <- weekly %>% ungroup() # ungroup is necessary for the plot later
head(weekly,2)
# make year a factor
weekly <- weekly %>% mutate(year = as.factor(year))

head(weekly,2)

# create the time series plot with one line for each year
ggplot(weekly, aes(x = week, y = n)) + 
  geom_line() + 
  geom_point(aes(color = year)) +  # included to make the plot more readable 
  scale_x_continuous(breaks = seq(0,52,2))  # to make the x-axis more readable 
```




## 9. The end of VEISHEA
From Wikipedia: 
"VEISHEA was an annual week-long celebration held each spring on the campus of Iowa State University in Ames, Iowa. The celebration featured an annual parade and many open-house demonstrations of the university facilities and departments. Campus organizations exhibited products, technologies, and held fundraisers for various charity groups. In addition, VEISHEA brought speakers, lecturers, and entertainers to Iowa State. [...] VEISHEA was the largest student-run festival in the nation, bringing in tens of thousands of visitors to the campus each year."
This over 90-year tradition in Ames was terminated permanently after riots in 2014, where drunk celebrators flipped over multiple vehicles and tore light poles down. This was not the first incidence of violence and severe property damage in VEISHEA's history. Did former President Leath make the right decision?


```R
## Run this code to create the plot 
ggplot() + 
  geom_point(data = weekly, aes(x = week, y = n, color = year)) + 
  geom_line(data = weekly, aes(x = week, y = n, color = year)) +  # included to make the plot more readable 
  geom_segment(data = NULL, arrow = arrow(angle = 20, length = unit(0.1, "inches"),
                                          ends = "last", type = "closed"), 
               aes(x = c(20,20), xend = c(15.5,16), y = c(21, 20), yend = c(21, 12.25))) + 
  geom_text(data = NULL, aes(x = 23, y = 20.5, label = "VEISHEA Weeks"), size = 3) + 
  scale_x_continuous(breaks = seq(0,52,2)) 

## Make a decision about VEISHEA. TRUE or FALSE?  
cancelling_VEISHEA_was_right <- FALSE
```
